# Generated by Django 4.2.5 on 2024-08-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0002_remove_subscription_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
