# Generated by Django 4.2.5 on 2024-08-22 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0017_student_subscription_active_and_more'),
        ('Qiuzs', '0002_question_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LP_app.category'),
        ),
    ]
