# Generated by Django 4.2.5 on 2024-08-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='monthlysubscription',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
