# Generated by Django 4.2.5 on 2024-08-11 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0002_remove_lesson_category_remove_lesson_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LP_app.category'),
        ),
    ]
