# Generated by Django 4.2.5 on 2024-08-12 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0006_alter_student_alsaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='alsaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LP_app.grade'),
        ),
    ]
