# Generated by Django 4.2.5 on 2024-08-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0008_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='bdf',
            field=models.FileField(blank=True, null=True, upload_to='bdfs'),
        ),
    ]
