# Generated by Django 4.2.5 on 2024-08-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0012_alter_studentanswer_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='student',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
