# Generated by Django 4.2.5 on 2024-08-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0013_remove_studentanswer_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdfs')),
            ],
        ),
    ]
