# Generated by Django 4.2.5 on 2024-08-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0014_pdfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pdf_thumnale'),
        ),
    ]
