# Generated by Django 4.2.5 on 2024-08-18 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0015_pdfs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfs',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LP_app.grade'),
        ),
    ]
