# Generated by Django 4.2.5 on 2024-08-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0016_pdfs_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
