# Generated by Django 4.2.5 on 2024-08-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0018_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='is_used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
