# Generated by Django 4.2.5 on 2024-09-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0019_emailverification_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_courses',
        ),
    ]
