# Generated by Django 4.2.5 on 2024-09-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0020_remove_student_enrolled_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to='processed_videos/'),
        ),
    ]
